function init(self)
	msg.post(".", "acquire_input_focus")
	self.collision_id = nil
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
	self.collision_id = nil
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if not self.collision_id or go.get_position(self.collision_id).z < message.other_position.z then
			self.collision_id = message.other_id
		end	
	end
end

function on_input(self, action_id, action)
	go.set_position(vmath.vector3(action.screen_x, action.screen_y, 0))
	if action.released then
		print("Clicked on", self.collision_id)
	end
end

function on_reload(self)
    -- Add reload-handling code here
    -- Remove this function if not needed
end
